name: 'AWS ECS Scale up/down'
description: 'Update the desired number of tasks for an ECS service'
inputs:
  service:
    description: 'The name of the ECS service.'
    required: true
  cluster:
    description: 'The name of the ECS cluster the service belongs to.'
    required: true
  desired-count:
    description: 'The desired number of tasks to run in the service.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'